import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { NavLink, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import {
  AlertTriangle, Bell, Building2, Check, ChevronRight, CircleDollarSign, FileText,
  Headphones, LayoutDashboard, LogOut, Menu, Plus, Search, Settings, ShieldCheck,
  Store, Users, WalletCards, X, Eye, Download, MapPin, Star, Clock3, Send, CalendarDays,
} from 'lucide-react';
import { businessInvoices, businesses, customerInvoices, customers, verification, type Status } from './data';
import { downloadInvoicePdf, downloadStatementCsv } from './downloads';

type Role = 'business' | 'customer' | 'admin';

const money = (value: string) => <strong>{value}</strong>;

function StatusPill({ status }: { status: Status | string }) {
  return <span className={`status status-${status.toLowerCase().replaceAll(' ', '-')}`}>{status}</span>;
}

function Metric({ label, value, detail, tone = 'blue', icon }: { label: string; value: string; detail: string; tone?: string; icon?: ReactNode }) {
  return <article className={`metric metric-${tone}`}><div className="metric-head"><span>{label}</span>{icon}</div><strong>{value}</strong><small>{detail}</small></article>;
}

function Brand({ admin = false }: { admin?: boolean }) {
  return <div className="brand"><span className="brand-mark"><FileText size={18} /></span><div><b>HisabSajilo{admin ? ' Admin' : ''}</b><small>{admin ? 'Control Center' : 'Digital Billing'}</small></div></div>;
}

const navByRole: Record<Role, { label: string; path: string; icon: ReactNode }[]> = {
  business: [
    { label: 'Business Overview', path: '/boverview', icon: <LayoutDashboard size={18} /> },
    { label: 'Business Invoices', path: '/binvoice', icon: <FileText size={18} /> },
    { label: 'Business Customers', path: '/bcustomers', icon: <Users size={18} /> },
  ],
  customer: [
    { label: 'Customer Overview', path: '/coverview', icon: <LayoutDashboard size={18} /> },
    { label: 'Customer Invoices', path: '/cinvoice', icon: <FileText size={18} /> },
    { label: 'Explore Businesses', path: '/cdirectory', icon: <Store size={18} /> },
  ],
  admin: [
    { label: 'Account Verification', path: '/averify', icon: <ShieldCheck size={18} /> },
    { label: 'Flagged Reports', path: '/areports', icon: <AlertTriangle size={18} /> },
    { label: 'Support Tickets', path: '/asupport', icon: <Headphones size={18} /> },
  ],
};

const homeByRole: Record<Role,string> = { business:'/boverview', customer:'/coverview', admin:'/averify' };
const settingsByRole: Record<Role,string> = { business:'/bsettings', customer:'/csettings', admin:'/asettings' };

function Shell({ role, children, onLogout }: { role: Role; children: ReactNode; onLogout: () => void }) {
  const [open, setOpen] = useState(false);
  return <div className="app-shell">
    <aside className={open ? 'sidebar open' : 'sidebar'}>
      <div className="side-top"><Brand admin={role === 'admin'} /><button className="icon-btn side-close" onClick={() => setOpen(false)}><X size={18} /></button></div>
      <nav>{navByRole[role].map(item => <NavLink end={item.path.split('/').length === 2} key={item.path} to={item.path} onClick={() => setOpen(false)}>{item.icon}<span>{item.label}</span></NavLink>)}</nav>
      <div className="sidebar-bottom">
        <NavLink to={settingsByRole[role]}><Settings size={18} /> Settings</NavLink>
        <button onClick={onLogout}><LogOut size={18} /> Logout</button>
      </div>
    </aside>
    {open && <button className="scrim" aria-label="Close menu" onClick={() => setOpen(false)} />}
    <section className="main-shell">
      <header className="topbar"><button className="icon-btn menu-btn" onClick={() => setOpen(true)}><Menu size={20} /></button><div className="global-search"><Search size={17}/><input placeholder="Search invoices, customers..." /></div><div className="top-actions"><div className="fiscal-year" title="Current Nepali fiscal year"><CalendarDays size={15}/><span><small>Fiscal Year</small><b>2083/084</b></span></div><button className="icon-btn" aria-label="Notifications"><Bell size={18}/><i /></button><div className="avatar">{role === 'admin' ? 'AD' : role === 'business' ? 'FS' : 'AK'}</div><span className="profile-name">{role === 'admin' ? 'Admin User' : role === 'business' ? 'Fiscal Sathi' : 'Aarav Khadka'}</span></div></header>
      <main>{children}</main>
    </section>
  </div>;
}

function PageHeader({ title, subtitle, action }: { title: string; subtitle: string; action?: ReactNode }) {
  return <div className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>;
}

function AuthPage({ onLogin }: { onLogin: (role: Role) => void }) {
  const nav = useNavigate(); const [role, setRole] = useState<Role>('business'); const [show, setShow] = useState(false);
  function submit(e: FormEvent) { e.preventDefault(); onLogin(role); nav(homeByRole[role]); }
  return <div className="auth-page"><div className="auth-backdrop"><span className="float-orb orb-a"/><span className="float-orb orb-b"/></div><form className="auth-card" onSubmit={submit}>
    <Brand /><div className="auth-title"><h1>Welcome back</h1><p>Sign in to manage your digital billing</p></div>
    <div className="role-tabs">{(['business','customer','admin'] as Role[]).map(r => <button type="button" className={role===r?'active':''} onClick={()=>setRole(r)} key={r}>{r[0]!.toUpperCase()+r.slice(1)}</button>)}</div>
    <label>Email address<input required type="email" defaultValue={role==='admin'?'admin@hisabsajilo.com':'demo@hisabsajilo.com'} /></label>
    <label>Password<div className="password"><input required type={show?'text':'password'} defaultValue="password"/><button type="button" onClick={()=>setShow(!show)}><Eye size={17}/></button></div></label>
    <div className="form-row"><label className="check"><input type="checkbox"/> Remember me</label><a href="#forgot">Forgot password?</a></div>
    <button className="btn primary full">Sign in <ChevronRight size={17}/></button>
    <p className="auth-switch">Don’t have an account? <button type="button" onClick={()=>nav('/signup')}>Create one</button></p>
  </form></div>;
}

function SignupPage() {
  const nav = useNavigate(); const [role,setRole]=useState<'business'|'customer'>('business'); const [step,setStep]=useState(1); const [registrationType,setRegistrationType]=useState<'pan'|'nonpan'>('pan');
  return <div className="auth-page"><form className="auth-card signup-card" onSubmit={e=>{e.preventDefault(); nav('/login')}}><Brand/><div className="auth-title"><h1>Create your account</h1><p>Start sending and receiving digital bills</p></div>
    <div className="role-tabs"><button type="button" className={role==='business'?'active':''} onClick={()=>setRole('business')}>Business</button><button type="button" className={role==='customer'?'active':''} onClick={()=>setRole('customer')}>Customer</button></div>
    <div className="stepper"><span className="active">1</span><i/><span className={step===2?'active':''}>2</span><small>{step===1?'Account details':'Verification details'}</small></div>
    {step===1 ? <div className="form-grid"><label className="wide">{role==='business'?'Business name':'Full name'}<input required placeholder={role==='business'?'e.g. Everest Tech Solutions':'e.g. Aarav Khadka'}/></label><label>Phone number<input required placeholder="+977 98XXXXXXXX"/></label><label>Email address<input required type="email" placeholder="you@example.com"/></label>{role==='business'&&<label className="wide">Business type<select><option>Service Provider</option><option>Store</option><option>Restaurant</option><option>Freelancer</option></select></label>}<label>Password<input required type="password" placeholder="Minimum 8 characters"/></label><label>Confirm password<input required type="password" placeholder="Repeat password"/></label></div> : role==='business' ? <div className="form-grid"><div className="wide registration-choice"><button type="button" className={registrationType==='pan'?'active':''} onClick={()=>setRegistrationType('pan')}><b>PAN registered business</b><small>Tax details and PAN document</small></button><button type="button" className={registrationType==='nonpan'?'active':''} onClick={()=>setRegistrationType('nonpan')}><b>Non-PAN small business</b><small>Invoices without VAT or PAN fields</small></button></div>{registrationType==='pan'&&<><label className="wide">PAN number<input required placeholder="Enter PAN number"/></label><UploadField label="PAN document"/></>}<UploadField label="Fonepay QR" accept="image/*"/><UploadField label="Business registration document"/></div> : <div className="form-grid"><label>Document type<select required><option value="">Select document</option><option>Citizenship</option><option>National ID</option><option>Driving licence</option><option>Passport</option></select></label><label>Document number<input required placeholder="Enter document number"/></label><UploadField label="Document photo"/></div>}
    {step===1?<button type="button" className="btn primary full" onClick={()=>setStep(2)}>Continue <ChevronRight size={17}/></button>:<button className="btn primary full">Create account</button>}
    <p className="auth-switch">Already have an account? <button type="button" onClick={()=>nav('/login')}>Sign in</button></p>
  </form></div>;
}

function UploadField({label,accept='image/*,application/pdf'}:{label:string;accept?:string}) { return <label className="wide">{label}<span className="dropzone"><Download size={20}/><span>Choose a file</span><small>PNG, JPG or PDF up to 10MB</small><input required type="file" accept={accept}/></span></label> }

function MiniChart() { return <div className="chart"><div className="chart-labels"><span>NPR 0</span><span>NPR 50K</span></div><svg viewBox="0 0 600 190" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#1684d9" stopOpacity=".32"/><stop offset="1" stopColor="#1684d9" stopOpacity="0"/></linearGradient></defs><path className="grid" d="M0 35H600M0 85H600M0 135H600M0 185H600"/><path className="area" d="M0 155 C45 145 55 90 105 100 S170 155 215 120 S285 40 335 60 S410 110 455 75 S540 45 600 25 L600 190 L0 190Z"/><path className="line" d="M0 155 C45 145 55 90 105 100 S170 155 215 120 S285 40 335 60 S410 110 455 75 S540 45 600 25"/></svg><div className="months"><span>Jan</span><span>Mar</span><span>May</span><span>Jul</span><span>Sep</span><span>Nov</span></div></div> }

function InvoiceTable({ rows, customer = false, onView }: { rows: typeof businessInvoices; customer?: boolean; onView?: (id:string)=>void }) {
  return <div className="table-wrap"><table><thead><tr><th>Invoice ID</th><th>{customer?'Service provider':'Customer name'}</th><th>Due date</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><button className="link" onClick={()=>onView?.(row.id)}>{row.id}</button></td><td>{row.customer}</td><td>{row.date}</td><td>{money(row.amount)}</td><td><StatusPill status={row.status}/></td><td><button className="btn tiny outline" onClick={()=>onView?.(row.id)}>{customer&&row.status==='Pending'?'Pay now':'View'}</button></td></tr>)}</tbody></table></div>;
}

function BusinessOverview({ openInvoice }: { openInvoice:()=>void }) {
  const nav=useNavigate(); return <><PageHeader title="Overview" subtitle="Manage your invoices, track payments, and monitor your business." action={<button className="btn primary" onClick={openInvoice}><Plus size={17}/>Create invoice</button>}/>
  <div className="metric-grid four"><Metric label="Total monthly revenue" value="NPR 1,245,000" detail="↑ 12.5% from last month" tone="green" icon={<CircleDollarSign/>}/><Metric label="Pending settlements" value="NPR 320,500" detail="6 invoices awaiting payment" tone="orange" icon={<Clock3/>}/><Metric label="Verified transactions" value="142" detail="Successfully processed this month" tone="blue" icon={<ShieldCheck/>}/><Metric label="Tax audit readiness" value="98%" detail="All records synchronized" tone="green" icon={<Check/>}/></div>
  <section className="panel"><div className="panel-head"><div><h2>Active invoices</h2><p>Latest invoices and their payment status</p></div><button className="link" onClick={()=>nav('/binvoice')}>View all <ChevronRight size={14}/></button></div><InvoiceTable rows={businessInvoices} onView={(id)=>nav(`/binvoice/${id}`)}/></section></>;
}

function BusinessInvoices({ openInvoice }: { openInvoice:()=>void }) { const nav=useNavigate(); const [q,setQ]=useState(''); const rows=businessInvoices.filter(x=>(x.id+x.customer).toLowerCase().includes(q.toLowerCase())); return <><PageHeader title="Business invoices" subtitle="Create tax invoices, track payments, and maintain your sales register." action={<button className="btn primary" onClick={openInvoice}><Plus size={17}/>Create invoice</button>}/><div className="metric-grid two compact"><Metric label="Total billed" value="NPR 4,520,000" detail="Across all invoices"/><Metric label="Overdue amount" value="NPR 45,000" detail="Requires your attention" tone="red"/></div><section className="panel"><div className="filters"><div className="searchbox"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer..."/></div><select><option>All statuses</option><option>Paid</option><option>Pending</option></select><select><option>Last 30 days</option></select></div><InvoiceTable rows={rows} onView={id=>nav(`/binvoice/${id}`)}/></section></> }

function CustomerOverview() { const nav=useNavigate(); return <><PageHeader title="Customer overview" subtitle="Welcome back. Here is a summary of your recent service activities and financial status." action={<button className="btn outline" onClick={()=>downloadStatementCsv(customerInvoices,'customer-statement.csv')}><Download size={16}/>Download report</button>}/><section className="panel chart-panel"><div className="panel-head"><div><h2>Recent spending</h2><p>Your total expenses over the last 12 months</p></div><span className="delta">↑ 12.5% this month</span></div><div className="big-number">NPR 45,200 <small>.00</small></div><MiniChart/></section><div className="split"><section className="panel alert-panel"><div className="panel-head"><h2><AlertTriangle size={18}/> Action required</h2></div><div className="action-item"><div><b>Invoice INV-2025-034</b><span>TechNova Solutions · Due Aug 18</span><StatusPill status="Pending"/></div><b>NPR 15,000</b></div><button className="btn primary full" onClick={()=>nav('/cinvoice')}>Pay now</button></section><section className="panel"><div className="panel-head"><h2>Recent activity</h2><button className="link" onClick={()=>nav('/cinvoice')}>View all</button></div>{customerInvoices.slice(0,3).map(x=><div className="activity" key={x.id}><span className="activity-icon"><FileText size={16}/></span><div><b>{x.customer}</b><small>{x.date}</small></div><strong>{x.amount}</strong></div>)}</section></div></> }

function CustomerInvoices() { const nav=useNavigate(); const [q,setQ]=useState(''); const rows=customerInvoices.filter(x=>(x.id+x.customer).toLowerCase().includes(q.toLowerCase())); return <><PageHeader title="Customer invoices" subtitle="Manage your received bills and pending payments." action={<button className="btn outline" onClick={()=>downloadStatementCsv(rows,'customer-invoices.csv')}><Download size={16}/>Export statement</button>}/><div className="metric-grid three compact"><Metric label="Total due" value="NPR 45,200" detail="Across 3 pending invoices" tone="red"/><Metric label="Paid this year" value="NPR 128,500" detail="12 completed payments" tone="green"/><Metric label="Pending approval" value="3 invoices" detail="Action required soon" tone="orange"/></div><section className="panel"><div className="filters"><div className="searchbox"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by ID or provider..."/></div><select><option>Service type</option></select><select><option>Status</option></select></div><InvoiceTable rows={rows} customer onView={id=>nav(`/cinvoice/${id}`)}/></section></> }

function Directory({ toast }: { toast:(s:string)=>void }) { const [q,setQ]=useState(''); const [category,setCategory]=useState('All providers'); const filtered=businesses.filter(x=>(x.name+x.type).toLowerCase().includes(q.toLowerCase())&&(category==='All providers'||x.type.toLowerCase().includes(category.split(' ')[0]!.toLowerCase()))); return <><PageHeader title="Explore businesses" subtitle="Find verified businesses and service providers."/><div className="category-row">{['All providers','IT & Tech','Legal','Repair'].map(x=><button className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><div className="searchbox directory-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search businesses, services, or location..."/></div><div className="business-grid">{filtered.map(b=><article className="business-card" key={b.name}><div className="business-logo"><Building2/></div><div className="verified-row"><h3>{b.name}</h3>{b.verified&&<ShieldCheck size={16}/>}</div><p>{b.type}</p><div className="rating"><Star size={15} fill="currentColor"/> {b.rating}<span><MapPin size={14}/>{b.distance}</span></div><dl><div><dt>Avg. service</dt><dd>{b.price}</dd></div></dl><div className="card-actions"><button className="btn outline" onClick={()=>toast(`${b.name} profile opened`)}>Details</button><button className="btn primary" onClick={()=>toast(`Service request sent to ${b.name}`)}>Book service</button></div></article>)}</div>{filtered.length===0&&<div className="empty-state">No businesses match this filter.</div>}</> }

function CustomerDirectory({ toast }: { toast:(s:string)=>void }) { const [q,setQ]=useState(''); const rows=customers.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())); return <><PageHeader title="Business customer directory" subtitle="Manage clients, payment status, and billing history." action={<button className="btn primary" onClick={()=>toast('New customer form opened')}><Plus size={16}/>Add new customer</button>}/><section className="panel"><div className="filters"><div className="searchbox"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by name, PAN, or email..."/></div><select><option>All customers</option></select></div><div className="customer-cards">{rows.map(c=><article key={c.name}><div className="customer-avatar">{c.name.split(' ').map(x=>x[0]).slice(0,2)}</div><div><h3>{c.name}</h3><p>{c.contact} · PAN {c.pan}</p><small>{c.invoices} invoices · {c.total}</small></div><StatusPill status={c.status}/><button className="icon-btn" onClick={()=>toast(`${c.name} details opened`)}><ChevronRight size={18}/></button></article>)}</div></section></> }

function AdminVerification({ toast }: { toast:(s:string)=>void }) { return <><PageHeader title="Account verification queue" subtitle="Review and approve pending accounts to grant platform access." action={<StatusPill status="4 Pending"/>}/><div className="notice"><ShieldCheck/><div><b>Restricted access protocol active</b><span>Accounts flagged for review can only access verification and support until approved.</span></div></div><section className="panel"><div className="filters"><div className="searchbox"><Search size={16}/><input placeholder="Search entity or PAN..."/></div><select><option>All types</option></select></div><div className="table-wrap"><table><thead><tr><th>Entity name</th><th>Type</th><th>Submission date</th><th>PAN / ID</th><th>Verification status</th><th>Actions</th></tr></thead><tbody>{verification.map(x=><tr key={x.entity}><td><b>{x.entity}</b></td><td>{x.type}</td><td>{x.date}</td><td>{x.pan}</td><td><StatusPill status={x.status}/></td><td><div className="inline-actions"><button className="btn tiny outline" onClick={()=>toast(`${x.entity} rejected`)}>Reject</button><button className="btn tiny primary" onClick={()=>toast(`${x.entity} verified`)}>Verify</button></div></td></tr>)}</tbody></table></div></section></> }

function Reports({ toast }: { toast:(s:string)=>void }) { return <><PageHeader title="Flagged invoices" subtitle="Review and resolve suspicious invoice disputes."/><div className="notice danger"><AlertTriangle/><div><b>Strict penalty warning</b><span>Falsely created or misstated invoices may result in immediate account suspension.</span></div></div><section className="panel"><InvoiceTable rows={[businessInvoices[2]!,businessInvoices[3]!]} onView={()=>toast('Report opened for review')}/></section></> }

function Support() { const [selected,setSelected]=useState(0); const [resolved,setResolved]=useState(false); const [message,setMessage]=useState(''); const [messages,setMessages]=useState(['Hello, I paid this invoice but it is still showing as pending.','Thanks for reaching out. Please share the payment reference and we’ll investigate.']); const tickets=['Refund not received','Unable to verify PAN','Incorrect invoice amount']; return <><PageHeader title="Support center" subtitle="Resolve customer and business requests."/><section className="support-layout"><div className="ticket-list"><div className="searchbox"><Search size={16}/><input placeholder="Search tickets..."/></div>{tickets.map((x,i)=><button className={selected===i?'active':''} onClick={()=>{setSelected(i);setResolved(false)}} key={x}><span className="customer-avatar">{['AK','AS','HT'][i]}</span><div><b>{x}</b><small>Ticket #HS-00{i+281} · {i+1}h ago</small></div><StatusPill status={resolved&&selected===i?'Resolved':i===0?'Pending':'Open'}/></button>)}</div><div className="conversation"><div className="conversation-head"><div><h2>{tickets[selected]}</h2><p>Ticket #HS-00{selected+281}</p></div><button className="btn outline" onClick={()=>setResolved(!resolved)}>{resolved?'Reopen':'Resolve'}</button></div><div className="messages">{messages.map((m,i)=><div key={i} className={i%2?'message mine':'message'}>{m}<small>{i%2?'Admin · 10:34':'Aarav · 10:28'}</small></div>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();if(message.trim()){setMessages([...messages,message]);setMessage('')}}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Type your reply..."/><button className="btn primary"><Send size={16}/>Send</button></form></div></section></> }

function SettingsPage({ role }: { role: Role }) { const [tickets,setTickets]=useState<string[]>([]); const [subject,setSubject]=useState(''); return <><PageHeader title="Settings" subtitle="Manage your profile, notifications, and support requests."/><div className="settings-grid"><section className="panel"><h2>Profile information</h2><div className="form-grid"><label>Display name<input defaultValue={role==='business'?'Fiscal Sathi':role==='admin'?'Admin User':'Aarav Khadka'}/></label><label>Email<input defaultValue={`${role}@hisabsajilo.com`}/></label><label className="wide">Phone number<input defaultValue="+977 9800000000"/></label></div><button className="btn primary">Save changes</button></section><section className="panel"><h2>Notifications</h2>{['Payment updates','New invoice alerts','KYC and security notices'].map(x=><label className="toggle-row" key={x}><span>{x}<small>Receive important account updates</small></span><input type="checkbox" defaultChecked/></label>)}</section>{role!=='admin'&&<section className="panel support-settings"><h2>Create a support ticket</h2><p>Describe the issue and our support team will reply in the support center.</p><form className="form-grid" onSubmit={e=>{e.preventDefault();setTickets([...tickets,subject]);setSubject('')}}><label>Category<select required><option>Invoice or agreement</option><option>Account verification</option><option>Payment</option><option>Other</option></select></label><label>Priority<select required><option>Normal</option><option>High</option></select></label><label className="wide">Subject<input required value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Short summary"/></label><label className="wide">Message<textarea required placeholder="Tell us what happened..."/></label><button className="btn primary">Submit ticket</button></form>{tickets.map((ticket,i)=><div className="created-ticket" key={`${ticket}-${i}`}><div><b>{ticket}</b><small>Ticket #HS-{301+i} · just now</small></div><StatusPill status="Open"/></div>)}</section>}</div></> }

function InvoiceDetail({ role, toast }: { role: Role; toast:(s:string)=>void }) {
  const {pathname}=useLocation();
  const id=pathname.split('/').pop()!;
  const invoice=[...businessInvoices,...customerInvoices].find(x=>x.id===id)??businessInvoices[0]!;
  const vatRegistered = role==='business' || !['Himalayan Legal','Himalayan Merchants'].includes(invoice.customer);
  const [currentStatus,setCurrentStatus]=useState<Status|string>(invoice.status==='Pending'?'Awaiting response':invoice.status); const [countering,setCountering]=useState(false); const [counterAmount,setCounterAmount]=useState('15000'); const [counterNote,setCounterNote]=useState(''); const [reported,setReported]=useState(false);
  const subtotal=vatRegistered?13274:15000; const vat=vatRegistered?1726:0; const total=subtotal+vat;
  const seller=role==='business'?'Fiscal Sathi Pvt. Ltd.':invoice.customer;
  const buyer=role==='business'?invoice.customer:'Aarav Khadka';
  const isFinal=['Paid','Verified','Completed'].includes(currentStatus); const agreementActive=!isFinal&&!['Rejected','Cancelled'].includes(currentStatus);
  const download=()=>void downloadInvoicePdf({id:invoice.id,seller,buyer,date:invoice.date,status:currentStatus,subtotal,vat,total,vatRegistered});
  return <>
    <PageHeader title={invoice.id} subtitle={isFinal?(vatRegistered?'Final Nepal VAT bill':'Final non-VAT sales bill'):'Invoice agreement — negotiate before billing'} action={<div className="inline-actions responsive-actions">{isFinal&&<button className="btn outline" onClick={download}><Download size={16}/>Download bill</button>}<button className="btn outline danger-btn" onClick={()=>{setReported(true);toast('Invoice report submitted to the admin review queue')}}><AlertTriangle size={16}/>{reported?'Reported':'Report'}</button></div>}/>
    {!isFinal&&<div className="notice agreement-notice"><FileText/><div><b>This invoice is an agreement proposal, not a final bill</b><span>Either party may accept, reject, or counter it. A standard bill is issued only after the agreement and payment process are complete.</span></div></div>}
    <div className="invoice-layout"><section className="panel invoice-paper nepali-bill">
      <div className="tax-title"><div><b>{isFinal?(vatRegistered?'कर बिजक / TAX INVOICE':'बिल / SALES BILL'):'सेवा सम्झौता / SERVICE AGREEMENT'}</b><span>{isFinal?(vatRegistered?'Original / Taxable Supply':'Non-VAT registered seller'):'Proposal open for mutual confirmation'}</span></div><StatusPill status={currentStatus}/></div>
      <div className="invoice-brand"><Brand/><div className="invoice-meta"><b>{invoice.id}</b><span>Invoice date: {invoice.date}</span><span>Due date: {invoice.date}</span></div></div>
      <div className="invoice-parties"><div><small>SELLER / विक्रेता</small><b>{seller}</b><span>New Baneshwor, Kathmandu, Nepal</span><span>PAN: 302145678</span>{vatRegistered&&<span className="vat-number">VAT No: 302145678</span>}</div><div><small>BUYER / खरिदकर्ता</small><b>{buyer}</b><span>Kathmandu, Nepal</span><span>PAN: {role==='business'?'601249830':'—'}</span></div></div>
      <div className="table-wrap"><table className="bill-items"><thead><tr><th>S.N.</th><th>Particulars</th><th>Qty</th><th>Rate</th><th>{isFinal?'Taxable amount':'Proposed amount'}</th></tr></thead><tbody><tr><td>1</td><td>Professional service charge</td><td>1</td><td>NPR {subtotal.toLocaleString()}</td><td>NPR {subtotal.toLocaleString()}</td></tr></tbody></table></div>
      <div className="totals"><span>{isFinal?'Subtotal':'Proposed subtotal'} <b>NPR {subtotal.toLocaleString()}</b></span>{isFinal&&vatRegistered&&<span>VAT @ 13% <b>NPR {vat.toLocaleString()}</b></span>}<span className="grand">{isFinal?'Grand total':'Agreement value'} <b>NPR {(isFinal?total:subtotal).toLocaleString()}</b></span></div>
      <div className="amount-words">Amount in words: <b>{vatRegistered?'Fifteen thousand rupees only':'Fifteen thousand rupees only'}</b></div>
      <div className="bill-footer"><div><span>Payment method</span><b>Fonepay QR / Bank transfer</b></div><div className="signature"><i/><b>Authorized signature</b></div></div>
      <div className="legal-note">{isFinal?(vatRegistered?'VAT is charged because the seller profile is VAT registered. This prototype is not an IRD-certified billing system.':'No VAT amount or VAT registration number is shown because the seller is not VAT registered.'):'Tax treatment is shown only on the final bill. This agreement records the proposed scope and price.'}</div>
    </section><aside className="panel timeline"><h2>{isFinal?'Transaction history':'Agreement actions'}</h2>{['Proposal created','Sent to the other party','Proposal viewed'].map((x,i)=><div className="timeline-item" key={x}><span><Check size={13}/></span><div><b>{x}</b><small>{i===0?'Aug 08, 09:42':'Aug 08, 10:15'}</small></div></div>)}{agreementActive&&<><div className="agreement-actions"><button className="btn primary" onClick={()=>{setCurrentStatus('Agreed');setCountering(false);toast('Agreement accepted')}}><Check size={15}/>Accept</button><button className="btn outline" onClick={()=>setCountering(true)}><CircleDollarSign size={15}/>Counter</button><button className="btn outline danger-btn" onClick={()=>{setCurrentStatus('Rejected');setCountering(false);toast('Agreement rejected')}}><X size={15}/>Reject</button></div>{countering&&<form className="counter-form" onSubmit={e=>{e.preventDefault();setCurrentStatus('Countered');setCountering(false);toast(`Counter offer of NPR ${Number(counterAmount).toLocaleString()} sent`)}}><label>Counter amount<input required type="number" min="1" value={counterAmount} onChange={e=>setCounterAmount(e.target.value)}/></label><label>Note<textarea required value={counterNote} onChange={e=>setCounterNote(e.target.value)} placeholder="Explain your proposed change"/></label><button className="btn primary full">Send counter offer</button></form>}</>}<div className="timeline-item pending"><span><Clock3 size={13}/></span><div><b>{isFinal?'Final bill issued':currentStatus}</b><small>{isFinal?`Paid ${invoice.date}`:'Awaiting the other party'}</small></div></div></aside></div>
  </>
}

function CreateInvoiceModal({ close, toast }: { close:()=>void; toast:(s:string)=>void }) {
  const [vatRegistered,setVatRegistered]=useState(true);
  const [items,setItems]=useState([{description:'',quantity:1,price:0}]); const [phone,setPhone]=useState('');
  const normalized=phone.replace(/\D/g,'').replace(/^977/,''); const matches:Record<string,string>={'9800000002':'Test Customer','9812345678':'Aarav Khadka','9841000000':'Bikash Sharma'}; const detectedCustomer=matches[normalized];
  const subtotal=useMemo(()=>items.reduce((a,x)=>a+x.quantity*x.price,0),[items]);
  const vat=vatRegistered?subtotal*.13:0;
  return <div className="modal-backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();if(!detectedCustomer)return;toast(`Agreement proposal sent to ${detectedCustomer}`);close()}}>
    <div className="modal-head"><div><h2>Create invoice agreement</h2><p>Send proposed service and pricing details for the customer to accept, reject, or counter.</p></div><button type="button" className="icon-btn" onClick={close}><X/></button></div>
    <label className="vat-toggle"><span><b>VAT registered business</b><small>Demo control — Supabase enforces this from the business profile.</small></span><input type="checkbox" checked={vatRegistered} onChange={e=>setVatRegistered(e.target.checked)}/></label>
    <div className="form-grid"><label className="wide">Customer phone number<input required inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="98XXXXXXXX"/></label>{detectedCustomer&&<div className="wide customer-detected"><Check size={17}/><div><b>{detectedCustomer}</b><small>Registered customer · {normalized}</small></div></div>}{normalized.length>=10&&!detectedCustomer&&<div className="wide lookup-error">No registered customer found for this phone number.</div>}<label>Agreement date<input required type="date"/></label><label>Valid until<input required type="date"/></label><label>Preferred payment<select><option>Fonepay QR</option><option>Bank transfer</option><option>Cash</option></select></label>{vatRegistered&&<label>Seller VAT number<input readOnly value="302145678"/></label>}</div>
    <h3>Goods / services</h3>{items.map((item,i)=><div className="line-item vat-line" key={i}><input required placeholder="Particulars" value={item.description} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><input aria-label="Quantity" type="number" min="1" value={item.quantity} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,quantity:+e.target.value}:x))}/><input aria-label="Unit price" type="number" min="0" placeholder="Unit price" onChange={e=>setItems(items.map((x,j)=>j===i?{...x,price:+e.target.value}:x))}/>{items.length>1&&<button type="button" className="icon-btn" onClick={()=>setItems(items.filter((_,j)=>j!==i))}><X size={16}/></button>}</div>)}
    <button type="button" className="btn ghost" onClick={()=>setItems([...items,{description:'',quantity:1,price:0}])}><Plus size={16}/>Add item</button>
    <div className="modal-total"><span>Proposed subtotal <b>NPR {subtotal.toLocaleString()}</b></span><strong>Agreement value NPR {subtotal.toLocaleString()}</strong><small>VAT is calculated only when the final bill is issued.</small></div>
    <div className="modal-actions"><button type="button" className="btn outline" onClick={close}>Cancel</button><button disabled={!detectedCustomer} className="btn primary">Send agreement</button></div>
  </form></div>
}

export function App() {
  const [role,setRole]=useState<Role|null>(()=>(localStorage.getItem('bs-role') as Role|null)); const [modal,setModal]=useState(false); const [toast,setToast]=useState('');
  function login(r:Role){localStorage.setItem('bs-role',r);setRole(r)} function logout(){localStorage.removeItem('bs-role');setRole(null)} function notify(s:string){setToast(s);window.setTimeout(()=>setToast(''),2800)}
  const gated=(required:Role,page:ReactNode)=>role===required?page:<Navigate to={role?homeByRole[role]:'/login'} replace/>;
  return <><Routes><Route path="/login" element={<AuthPage onLogin={login}/>}/><Route path="/signup" element={<SignupPage/>}/><Route path="*" element={!role?<Navigate to="/login" replace/>:<Shell role={role} onLogout={logout}><Routes>
    <Route path="/boverview" element={gated('business',<BusinessOverview openInvoice={()=>setModal(true)}/>)}/><Route path="/binvoice" element={gated('business',<BusinessInvoices openInvoice={()=>setModal(true)}/>)}/><Route path="/binvoice/:id" element={gated('business',<InvoiceDetail role="business" toast={notify}/>)}/><Route path="/bcustomers" element={gated('business',<CustomerDirectory toast={notify}/>)}/><Route path="/bsettings" element={gated('business',<SettingsPage role="business"/> )}/>
    <Route path="/coverview" element={gated('customer',<CustomerOverview/>)}/><Route path="/cinvoice" element={gated('customer',<CustomerInvoices/>)}/><Route path="/cinvoice/:id" element={gated('customer',<InvoiceDetail role="customer" toast={notify}/>)}/><Route path="/cdirectory" element={gated('customer',<Directory toast={notify}/>)}/><Route path="/csettings" element={gated('customer',<SettingsPage role="customer"/>)}/>
    <Route path="/averify" element={gated('admin',<AdminVerification toast={notify}/>)}/><Route path="/areports" element={gated('admin',<Reports toast={notify}/>)}/><Route path="/asupport" element={gated('admin',<Support/>)}/><Route path="/asettings" element={gated('admin',<SettingsPage role="admin"/>)}/>
    <Route path="/business/*" element={<Navigate to="/boverview" replace/>}/><Route path="/customer/*" element={<Navigate to="/coverview" replace/>}/><Route path="/admin/*" element={<Navigate to="/averify" replace/>}/><Route path="*" element={<Navigate to={homeByRole[role]} replace/>}/>
  </Routes></Shell>}/></Routes>{modal&&<CreateInvoiceModal close={()=>setModal(false)} toast={notify}/>} {toast&&<div className="toast"><Check size={17}/>{toast}</div>}</>;
}
